### ISSUE TITLE
test code/data

### ISSUE THREAD

**Issue by calmeRED** [jasdeep-singh-007/Multi-Domain-Learning-for-Motion-Magnification#2]
Is it possible for your team to release the test code and the test data? I'm looking forward to it!

**Comment by jasdeep-singh-007** [comment]
i have released the test code nad details of test data can be found in the supplementry material

**Comment by jasdeep-singh-007** [comment]
> i have released the test code and details of test data can be found in the supplementry material.

**Comment by calmeRED** [comment]
By test code I mean the test code for physical accuracy test, and the physical accuracy data, will your team release it in the future?
